spring.application.name=nexcart-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/nexcart
spring.datasource.username=postgres
spring.datasource.password=@rushi

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
.\mvnw.cmd spring-boot:run
server.port=8080